import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const filename=process.argv[2]||new URL('../app/terrain.ts',import.meta.url);
const source=fs.readFileSync(filename,'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace("'./sediment'",JSON.stringify(new URL('../app/sediment.ts',import.meta.url).href));
const {createTerrain,drawGrain}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
let nextId=0,now=0,resizeObserver,draws=0,uploads=0,allocations=0,callbackCount=0;
const raf=new Map(),events=new Map(),canvasEvents=new Map();
globalThis.requestAnimationFrame=fn=>{const id=++nextId;raf.set(id,fn);return id;};
globalThis.cancelAnimationFrame=id=>raf.delete(id);
globalThis.document={hidden:false};
globalThis.window={devicePixelRatio:1,addEventListener:(name,fn)=>events.set(name,fn),removeEventListener:name=>events.delete(name)};
globalThis.ResizeObserver=class{constructor(fn){resizeObserver=fn;}observe(){}disconnect(){}};
const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:()=>0,drawArrays(){draws++;},texImage2D(){allocations++;},texSubImage2D(){uploads++;}}, {get:(target,key)=>key in target?target[key]:()=>({})});
let width=1200,height=760;
const canvas={width:0,height:0,getContext:()=>gl,getBoundingClientRect:()=>({width,height}),addEventListener:(key,fn)=>canvasEvents.set(key,fn),removeEventListener:key=>canvasEvents.delete(key)};
const model={version:0,pack(){},stats:()=>({maxHeight:70})};
const state={model,altitude:260,yaw:0,view:'aerial'};
const cleanup=createTerrain(canvas,state,e=>{throw new Error(e);});
function frame(){now+=1000/60;const callbacks=[...raf.values()];raf.clear();for(const fn of callbacks){callbackCount++;fn(now);}}
frame();const initial=draws;
for(let i=0;i<120;i++)frame();const idle=draws-initial;
for(let i=0;i<120;i++){if(i%12===0)model.version++;frame();}const playing=draws-initial-idle;
const results={initialDraws:initial,idleDrawsOver2Seconds:idle,drawsAt5CyclesPerSecond:playing};
if(process.argv[3]==='baseline'){console.log(JSON.stringify(results));cleanup();process.exit(0);}
assert.equal(initial,1);assert.equal(idle,0);assert.equal(playing,10);assert.equal(allocations,1);assert.equal(uploads,10);
let before=draws;for(let i=0;i<30;i++){state.yaw+=.01;frame();}assert.equal(draws-before,30,'camera drag remains full frame rate');
state.altitude=600;state.view='above';before=draws;for(let i=0;i<300;i++)frame();assert.ok(draws>before,'altitude and viewpoint animate');before=draws;for(let i=0;i<120;i++)frame();assert.equal(draws,before,'settled camera stops redrawing');
width=800;resizeObserver();frame();assert.equal(draws,before+1,'resize redraws');assert.equal(canvas.width,720);assert.equal(canvas.height,684,'resolution remains 0.9x original CSS dimensions');
state.model.version++;document.hidden=true;before=draws;for(let i=0;i<60;i++)frame();assert.equal(draws,before);document.hidden=false;frame();assert.equal(draws,before+1,'hidden changes render on return');
state.view='grain';before=draws;state.model.version++;for(let i=0;i<60;i++)frame();assert.equal(draws,before,'grain view does not render hidden terrain');state.view='aerial';frame();assert.ok(draws>before);
cleanup();assert.equal(raf.size,0);assert.equal(events.size,0);assert.equal(canvasEvents.size,0);
let grainClears=0,grainWidth=800;
const context2D=new Proxy({clearRect(){grainClears++;},createLinearGradient:()=>({addColorStop(){}})},{get:(target,key)=>key in target?target[key]:()=>{}});
const grainCanvas={width:0,height:0,getContext:()=>context2D,getBoundingClientRect:()=>({width:grainWidth,height:600})};
drawGrain(grainCanvas,1);drawGrain(grainCanvas,1);assert.equal(grainClears,1,'paused grain view retains its drawing');
drawGrain(grainCanvas,2);assert.equal(grainClears,2,'grain motion updates');grainWidth=600;drawGrain(grainCanvas,2);assert.equal(grainClears,3,'paused grain view handles resize');
console.log(JSON.stringify({...results,cameraAndAltitude:true,resize:true,hiddenAndGrain:true,cleanup:true}));
