'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Layers, Maximize, Mountain, Pause, Play, RotateCcw, Plane, CircleDot, Download } from 'lucide-react';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { registerModelTools } from './model-tools';
import { createTerrain, drawGrain } from './terrain';
import { makeState, advanceSimulation, resetSimulation, windAt, type SimState } from './wind';

const scalar=(v:number|readonly number[])=>Array.isArray(v)?v[0]:v as number;
export default function Home(){
 const state=useRef<SimState>(makeState());const terrainRef=useRef<HTMLCanvasElement>(null);const grainRef=useRef<HTMLCanvasElement>(null);
 const [view,setView]=useState('aerial');const [playing,setPlaying]=useState(true);const [speed,setSpeed]=useState(5);const [strength,setStrength]=useState(1);const [altitude,setAltitude]=useState(310);const [years,setYears]=useState(0);const [info,setInfo]=useState(false);const [error,setError]=useState('');
 const [direction,setDirection]=useState(60);const [variableWind,setVariableWind]=useState(false);const [wind,setWind]=useState({direction:60,strength:1});
 const drag=useRef<{x:number,yaw:number}|null>(null);
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){state.current.playing=false;setPlaying(false);}return createTerrain(terrainRef.current!,state.current,setError);},[]);
 useEffect(()=>{let frame=0,prev=0,lastUI=0;function tick(now:number){const s=state.current;const dt=prev?Math.min((now-prev)/1000,.08):0;prev=now;if(!document.hidden)advanceSimulation(s,dt);if(now-lastUI>120){setYears(s.years);setWind(windAt(s));lastUI=now;}if(s.view==='grain'&&grainRef.current)drawGrain(grainRef.current,s.grainTime);frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
 function toggle(){state.current.playing=!state.current.playing;setPlaying(state.current.playing);}
 function reset(){resetSimulation(state.current);setYears(0);setWind(windAt(state.current));}
 function changeView(v:unknown){const next=String(v);state.current.view=next;setView(next);}
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{const el=e.target as HTMLElement;if(e.code==='Space'&&el.tagName!=='BUTTON'&&el.tagName!=='INPUT'&&el.getAttribute('role')!=='slider'&&!el.closest('[role="dialog"]')){e.preventDefault();toggle();}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
 useEffect(()=>registerModelTools(()=>state.current,input=>{
  if(input.reset)reset();
  if(input.playing!==undefined){state.current.playing=input.playing;setPlaying(input.playing);}
  if(input.view!==undefined)changeView(input.view);
  if(input.speed!==undefined){state.current.speed=input.speed;setSpeed(input.speed);}
  if(input.strength!==undefined){state.current.strength=input.strength;setStrength(input.strength);}
  if(input.direction!==undefined){state.current.direction=input.direction;setDirection(input.direction);}
  if(input.variableWind!==undefined){state.current.variableWind=input.variableWind;setVariableWind(input.variableWind);}
  setWind(windAt(state.current));
  if(input.altitude!==undefined){state.current.altitude=input.altitude;setAltitude(input.altitude);}
 }),[]);
 const rate=(base:number)=>`${(base*wind.strength).toFixed(1)} m/yr`;
 const bearing=['N','NE','E','SE','S','SW','W','NW'][Math.round(wind.direction/45)%8];
 return <main className={`app ${view==='grain'?'grain-mode':''}`}>
  <header className="masthead"><div className="brand"><Mountain strokeWidth={1.1}/><span>DUNE</span><span className="edition">A field in motion</span></div><div className="header-actions"><a className="quiet-button download-link" href="/a-sea-of-sand.html" download="a-sea-of-sand.html" title="Download a self-contained HTML file" aria-label="Download HTML simulation"><Download/><span>HTML</span></a><button className="quiet-button" onClick={()=>setInfo(true)}><BookOpen/>The science</button><button className="quiet-button" aria-label="Toggle fullscreen" title="Fullscreen" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize/></button></div></header>
  <section className="scene" aria-label="Interactive dune migration simulation">
   <canvas ref={terrainRef} className="terrain" aria-label="An aerial view of migrating dunes. Smaller ridges move faster than large dunes. Drag left or right to turn the camera." role="img" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();state.current.yaw+=(e.key==='ArrowRight'?.08:-.08);}}} onPointerDown={e=>{drag.current={x:e.clientX,yaw:state.current.yaw};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current)state.current.yaw=drag.current.yaw-(e.clientX-drag.current.x)*.003;}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>
   {view==='grain'&&<div className="grain-scene"><canvas ref={grainRef} role="img" aria-label="Cross-section: sand grains hop up the gentle slope, cross the crest, and fall down the slip face."/><p className="grain-annotation">Grains hop up the gentle slope, then fall down the steep face. Each journey moves a little sand downwind.</p><div className="grain-legend"><i/>A highlighted grain · motion slowed for clarity</div></div>}
   <div className="scene-heading"><p className="eyebrow"><span className="live-dot"/>{view==='grain'?'Inside a moving dune':'Desert observatory / Time-lapse'}</p><h1>{view==='grain'?'The shape travels.':'A sea of sand.'}</h1><p>{view==='grain'?'The dune moves because its grains do.':'An ocean whose clock runs in centuries. Watch the desert move.'}</p></div>
   <Tabs className="view-tabs" value={view} onValueChange={changeView}><TabsList aria-label="Viewpoint"><TabsTrigger value="aerial"><Plane/>Aerial</TabsTrigger><TabsTrigger value="above"><Layers/>Above</TabsTrigger><TabsTrigger value="grain"><CircleDot/>Grain journey</TabsTrigger></TabsList><TabsContent value="aerial">Oblique view from a stationary aircraft viewpoint</TabsContent><TabsContent value="above">Vertical view over the dunes</TabsContent><TabsContent value="grain">Schematic cross-section of grain transport</TabsContent></Tabs>
   <aside className="wind-panel" aria-label="Simulation controls"><div className="panel-label">Shaped by the wind</div><div className="wind-reading"><div className="compass"><span className="compass-north">N</span><ArrowUpRight style={{transform:`rotate(${wind.direction-45}deg)`}}/></div><div><strong>{wind.strength===0?'Calm':variableWind?'Changing wind':'Steady wind'}</strong><small>Toward {bearing} · {Math.round(wind.direction)%360}°</small></div></div>
   <div className="control"><div className="control-title"><label id="wind-label" title="A sand-transport multiplier; 0× stops migration">Wind strength</label><output>{strength.toFixed(1)}×</output></div><Slider aria-labelledby="wind-label" min={0} max={2} step={.1} value={[strength]} onValueChange={v=>{const n=scalar(v);setStrength(n);state.current.strength=n;}}/></div>
   <div className="control"><div className="control-title"><label id="direction-label">{variableWind?'Mean direction':'Wind toward'}</label><output>{direction}°</output></div><Slider aria-labelledby="direction-label" min={0} max={360} step={5} value={[direction]} onValueChange={v=>{const n=scalar(v);setDirection(n);state.current.direction=n;setWind(windAt(state.current));}}/></div>
   <div className="wind-auto"><label htmlFor="variable-wind">Vary automatically</label><Switch id="variable-wind" checked={variableWind} onCheckedChange={v=>{setVariableWind(v);state.current.variableWind=v;setWind(windAt(state.current));}}/></div>
   <p className="wind-mode-note">{variableWind?'Direction swings and strength pulses over time.':'Set a direction, or let the wind shift over time.'}</p>
   <div className="control"><div className="control-title"><label id="altitude-label">Altitude</label><output>{altitude} m</output></div><Slider aria-labelledby="altitude-label" min={160} max={700} step={10} value={[altitude]} onValueChange={v=>{const n=scalar(v);setAltitude(n);state.current.altitude=n;}}/></div>
   <div className="panel-rule"/><div className="panel-label">Illustrative migration</div><div className="migration"><span>Small · 15 m tall</span><strong>{rate(8)}</strong></div><div className="migration"><span>Large · 60 m tall</span><strong>{rate(2)}</strong></div></aside>
   {error&&view!=='grain'&&<div className="error-overlay"><p>{error}</p><button className="quiet-button" onClick={()=>changeView('grain')}>Explore Grain journey <ArrowRight/></button></div>}
   <div className="scene-bottom"><div><div className="time-label">{view==='grain'?'Grain transport':'Time elapsed'}</div><div className="time-value">{view==='grain'?'Hop. Fall. Repeat.':Math.floor(years).toLocaleString('en-GB')}{view!=='grain'&&<span>years</span>}</div></div><div className="scene-hint">{view==='grain'?<>Section aligned with wind<br/>Separate clock · aerial time paused</>:<><span className="drag-hint">Drag to look around · ← → to turn<br/></span>{view==='above'?'Vertical observation':'Stationary aerial observation'}<br/>Illustrative landscape</>}</div></div>
  </section>
  <div className="transport" aria-label="Playback controls"><button className="play-button" onClick={toggle} aria-label={playing?'Pause simulation':'Play simulation'} title="Play / pause (Space)">{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button className="reset-button" aria-label="Reset elapsed time and camera" title="Restart" onClick={reset}><RotateCcw size={16}/></button><span className="clock-state">{playing?'Time flowing':'Time paused'}</span><div className="speed-control"><label id="speed-label">Time speed</label><Slider aria-labelledby="speed-label" min={1} max={50} step={1} value={[speed]} onValueChange={v=>{const n=scalar(v);setSpeed(n);state.current.speed=n;}}/><output>{view==='grain'?`${(speed/5).toFixed(1)}×`:`${speed} yr/s`}</output></div><p className="transport-note">{view==='grain'?'See how sand carries the dune forward.':<>Watch the <span>smaller ridges</span> overtake the larger forms.</>}</p></div>
  <footer className="bottom-caption"><p><em>Sand moves. The shape travels.</em><span>A travelling wave made of grains.</span></p><button className="caption-link" onClick={()=>setInfo(true)}>Why dunes move <ArrowRight size={16}/></button></footer>
  <Sheet open={info} onOpenChange={setInfo}><SheetContent className="info-sheet"><span className="eyebrow">Field notes / 01</span><SheetTitle>A travelling waveform<br/>made of grains.</SheetTitle><SheetDescription>Wind gives sand a way to move. Time reveals the pattern.</SheetDescription><h3>Over the crest, down the face.</h3><p>Wind carries grains up the gentle windward slope in short hops and by surface creep. Sand accumulates at the crest, then avalanches down the sheltered slip face. The dune’s shape advances downwind.</p><h3>Small dunes get there first.</h3><p>Under similar sand-transport conditions, a smaller mobile dune generally travels faster. This model gives a 15 m dune four times the speed of a 60 m dune. Real dunes can exchange sand, merge, split, and reorganise when they meet.</p><h3>Waves riding on waves.</h3><p>Small dunes can ride over much larger dunes. Tiny surface ripples can adjust to changing winds within minutes; large dune fields evolve over centuries and longer. The fine texture in the aerial view suggests ripples, enlarged for visibility.</p><h3>A change in the wind.</h3><p>Choose the direction the wind blows toward, or enable automatic variation to make its direction swing and its strength pulse. Stronger transport moves both dune sizes faster. Changing wind alters their next movement without jumping the landscape to a new position.</p><h3>An ocean with a different clock.</h3><p>Both landscapes form patterns under a flowing fluid. But a migrating dune also transports sand downwind. Ocean waves primarily carry energy; water parcels mainly move back and forth, with some drift.</p><p className="model-note">Illustrative, accelerated motion. Shapes are procedural and the rates are examples, not measurements of the Sahara. This visualisation does not calculate grain transport or conserve sediment locally. Overlapping ridges suggest interaction; they are not a physical collision model. Wind strength is a simplified transport multiplier, not a measured wind speed. Direction steers pattern migration; this model does not solve the slow realignment of dune faces after a wind shift. The grain journey is a separate schematic, with motion slowed for clarity.</p><div className="sources">Read more:<br/><a href="https://pubs.usgs.gov/gip/deserts/eolian/" target="_blank" rel="noreferrer">USGS · Eolian processes ↗</a><br/><a href="https://www.nature.com/articles/s41467-022-30031-1" target="_blank" rel="noreferrer">Gunn et al. · What sets aeolian dune height? ↗</a><br/><a href="https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2025JF008616" target="_blank" rel="noreferrer">Nield et al. · Sand ripple dynamics ↗</a></div></SheetContent></Sheet>
 </main>;
}
